// @no-log
POST http://localhost:3000/api/challenges
Content-Type: application/json

{ "name": "Roman Numerals", "content": "if(number < 1) throw new Error(\"Roman numerals doesn't support 0 or negative numbers.\");"}


###
// @no-log
GET http://localhost:3000/api/challenges

####
// @no-log
GET http://localhost:3000/api/challenges/GCCBIT1S

###
// @no-log
DELETE http://localhost:3000/api/challenges/GCCBIT1S
